version: 2.1

orbs:
  rebar3: tsloughter/rebar3@0.8.1
  codecov: codecov/codecov@1.0.5

jobs:
  codecov:
    parameters:
      executor:
        description: The executor to use for this job.
        type: executor
        default: erlang
    executor: <<parameters.executor>>
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/
      - run: 'rebar3 covertool generate'
      - codecov/upload:
          file: _build/test/covertool/opentelemetry.covertool.xml
      - codecov/upload:
          file: _build/test/covertool/opentelemetry_api.covertool.xml

  run_benchmarks:
    docker:
    - image: circleci/elixir:1.9
    steps:
    - checkout

    - run: |
        mix local.hex --force
        mix local.rebar --force

        rebar3 as bench compile

        ERL_LIBS=_build/bench/lib/ mix run --no-mix-exs samples/run.exs

erlang22: &erlang22
  executor:
    name: rebar3/erlang
    tag: "22"

erlang21: &erlang21
  executor:
    name: rebar3/erlang
    tag: "21"

workflows:
  otp21:
    jobs:
      - rebar3/compile:
          <<: *erlang21

  otp22:
    jobs:
      - rebar3/compile:
          <<: *erlang22
      - rebar3/xref:
          <<: *erlang22
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          <<: *erlang22
          requires:
            - rebar3/compile
      - rebar3/ct:
          <<: *erlang22
          requires:
            - rebar3/compile
      - rebar3/cover:
          <<: *erlang22
          requires:
            - rebar3/ct
      - codecov:
          <<: *erlang22
          requires:
            - rebar3/cover

  benchmarks:
    jobs:
      - run_benchmarks
