version: 2.1

orbs:
  rebar3: tsloughter/rebar3@0.8.1
  codecov: circleci/codecov@0.0.3

jobs:
  codecov:
    parameters:
      executor:
        description: The executor to use for this job.
        type: executor
        default: erlang
    executor: <<parameters.executor>>
    steps:
      - attach_workspace:
          at: ~/project/
      - codecov/upload:
          path: _build/test/covertool/opentelemetry.covertool.xml

erlang22: &erlang22
  executor:
    name: rebar3/erlang
    tag: "22"

workflows:
  otp22:
    jobs:
      - rebar3/compile:
          <<: *erlang22
      - rebar3/xref:
          <<: *erlang22
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          <<: *erlang22
          requires:
            - rebar3/compile
      - rebar3/ct:
          <<: *erlang22
          requires:
            - rebar3/compile
      - rebar3/cover:
          <<: *erlang22
          requires:
            - rebar3/ct
      - codecov:
          <<: *erlang22
          requires:
            - rebar3/cover
